development:
  adapter: postgresql
  database: funny_videos_development
  username: ciprian
  password: ciprian
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: funny_videos_test
  username: ciprian
  password: ciprian
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: funny_videos_production
  username: ciprian
  password: ciprian
  host: 127.0.0.1
  pool: 25
  timeout: 5000